apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: my-deploy
spec:
  replicas: 3
  template:
    metadata:
      name: my-deploy
      labels:
        app: my-deploy
    spec:
      containers:
        - name: nginx
          image: nginx:1.12
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: my-deploy
